-- Create quotes table
CREATE TABLE IF NOT EXISTS quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id BIGINT REFERENCES machines(id),
    client_id UUID REFERENCES profiles(id),
    landlord_id UUID REFERENCES profiles(id),
    rental_period TEXT NOT NULL,
    delivery_address TEXT NOT NULL,
    observations TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create quote_accessories table for many-to-many relationship
CREATE TABLE IF NOT EXISTS quote_accessories (
    quote_id BIGINT REFERENCES quotes(id) ON DELETE CASCADE,
    accessory_id BIGINT REFERENCES accessories(id) ON DELETE CASCADE,
    PRIMARY KEY (quote_id, accessory_id)
);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_quotes_updated_at
    BEFORE UPDATE ON quotes
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- Create RLS policies
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_accessories ENABLE ROW LEVEL SECURITY;

-- Policies for quotes
CREATE POLICY "Enable read access for authenticated users" ON quotes
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Enable insert for authenticated users" ON quotes
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Enable update for owner and landlord" ON quotes
    FOR UPDATE
    TO authenticated
    USING (
        auth.uid() = client_id OR 
        auth.uid() = landlord_id OR
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() 
            AND role = 'admin'
        )
    );

-- Policies for quote_accessories
CREATE POLICY "Enable read access for authenticated users" ON quote_accessories
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Enable insert for authenticated users" ON quote_accessories
    FOR INSERT
    TO authenticated
    WITH CHECK (true);
